### PR TITLE
Replace old phone number with new one

### PR DESCRIPTION
**Pull request by rid-x**

### CODE REVIEW

**Comment by arthurkhlghatyan** [comment]
Hey @rid-hrant,

From what I see you only published uglified JavaScript files, which makes it impossible to refactor the website. (Remove/change your photo, etc).

**Would you be able to commit all original source files to your branch?** 

Though not preferable but alternatively, you can drop the source files here - https://bit.ly/3Bj315Q 

Let me know if you need anything else to make the process more comfortable for you.

Cheers,

Arthur.

**Comment by rid-x** [comment]
Hi @arthurkhlghatyan, I can't provide the source code because I don't have it. Anyway, I think it's possible to change the phone number in uglified JS file. You can replace `{REPLACE_WITH_NEW_PHONE_NUMBER}` with the new phone number and it should work.

Screen Shot 2022-02-13 at 22 45 25

**Comment by arthurkhlghatyan** [comment]
Hi @rid-hrant 

Your commit contains diff for the main.js file which means you re-run the build.

Could you please double-check?

**Comment by arthurkhlghatyan** [comment]
Hey @rid-hrant 

Also, the source code is needed not just for the correction of the phone number, but also for removal of your contacts (photo and other data) and so on. 

So if you find the source code or figure out that you have it somewhere after the double-check, commit it please here.

Cheers,

Arthur.

**Pull request closed without merging**
